version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000" #NODE_PORT
    environment:
      - DB_URL="postgres://jamming:example@postgres/jamming"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: jamming
      POSTGRES_DB: jamming
    ports:
      - "5432:5432"
